<a href="https://colab.research.google.com/github/Armaanjeswani/Machine-learning/blob/main/movie_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

 Data Collection and Pre-processing

In [3]:
cols=['id', 'Name', 'Genre', 'Language', 'Summary', 'Popularity', 'Release date', 'Vote average', 'Rating']
movies_data=pd.read_csv("movies_data.csv",names=cols)

In [4]:
movies_data=movies_data.drop(['id','Release date','Vote average'],axis=1)

In [5]:
movies_data=movies_data.drop([0],axis=0)

In [6]:
idx=0
movies_data.insert(idx, 'index', value=np.arange(len(movies_data)))

In [7]:
movies_data


index                                           Name  \
1          0                       The Shawshank Redemption   
2          1                    Dilwale Dulhania Le Jayenge   
3          2                                  The Godfather   
4          3                               Schindler's List   
5          4                         The Godfather: Part II   
...      ...                                            ...   
9996    9995                             The Last Airbender   
9997    9996                       Sharknado 3: Oh Hell No!   
9998    9997                                Captain America   
9999    9998  In the Name of the King: A Dungeon Siege Tale   
10000   9999                                         Domino   

                                                  Genre Language  \
1                                           Drama,Crime       en   
2                                  Comedy,Drama,Romance       hi   
3                                           Drama,Crime       en   
4                                     Drama,History,War       en   
5                                           Drama,Crime       en   
...                                                 ...      ...   
9996                           Action,Adventure,Fantasy       en   
9997   Action,TV Movie,Science Fiction,Comedy,Adventure       en   
9998                         Action,Science Fiction,War       en   
9999                     Adventure,Fantasy,Action,Drama       en   
10000                             Thriller,Action,Crime       en   

                                                 Summary Popularity Rating  
1      Framed in the 1940s for the double murder of h...     94.075  21862  
2      Raj is a rich, carefree, happy-go-lucky second...     25.408   3731  
3      Spanning the years 1945 to 1955, a chronicle o...     90.585  16280  
4      The true story of how businessman Oskar Schind...     44.761  12959  
5      In the continuing saga of the Corleone crime f...     57.749   9811  
...                                                  ...        ...    ...  
9996   The story follows the adventures of Aang, a yo...     98.322   3347  
9997   The sharks take bite out of the East Coast whe...      12.49    417  
9998   During World War II, a brave, patriotic Americ...     18.333    332  
9999   A man named Farmer sets out to rescue his kidn...     15.159    668  
10000  Seeking justice for his partner’s murder by an...     16.482    221  

[10000 rows x 7 columns]

In [8]:
features=['Name', 'Genre', 'Language', 'Summary', 'Popularity', 'Rating']

In [9]:
#replacing null values with null strings
for i in features:
  movies_data[features]=movies_data[features].fillna('')


In [10]:
#Combining selected features
combined_features=movies_data['Genre']+' '+movies_data['Language']+' '+movies_data['Summary']+' '+movies_data['Popularity']+' '+movies_data['Rating']

In [11]:
print(combined_features)

1        Drama,Crime en Framed in the 1940s for the dou...
2        Comedy,Drama,Romance hi Raj is a rich, carefre...
3        Drama,Crime en Spanning the years 1945 to 1955...
4        Drama,History,War en The true story of how bus...
5        Drama,Crime en In the continuing saga of the C...
                               ...                        
9996     Action,Adventure,Fantasy en The story follows ...
9997     Action,TV Movie,Science Fiction,Comedy,Adventu...
9998     Action,Science Fiction,War en During World War...
9999     Adventure,Fantasy,Action,Drama en A man named ...
10000    Thriller,Action,Crime en Seeking justice for h...
Length: 10000, dtype: object


In [12]:
#Converting text to feature vectors
vectorizer=TfidfVectorizer()

In [13]:
feature_vectors=vectorizer.fit_transform(combined_features)

In [14]:
print(feature_vectors)

  (0, 1424)	0.1949156472897056
  (0, 78)	0.15108675883053535
  (0, 3576)	0.14489599947802312
  (0, 15331)	0.11303187398404875
  (0, 25715)	0.12704060155073385
  (0, 29792)	0.18661165870258398
  (0, 16285)	0.16652412278382958
  (0, 23850)	0.12560280739500476
  (0, 20313)	0.09046958826852002
  (0, 22911)	0.13878281656600894
  (0, 21063)	0.11628306572594936
  (0, 15941)	0.11158134539246463
  (0, 16163)	0.15506310425656059
  (0, 21292)	0.08314610655664303
  (0, 7088)	0.05049254542459134
  (0, 3960)	0.172415896449646
  (0, 5774)	0.06689542160187026
  (0, 8458)	0.09415367137627179
  (0, 27489)	0.15822013419670802
  (0, 18255)	0.09476053520800146
  (0, 11199)	0.08363217406155056
  (0, 30564)	0.15658084707258377
  (0, 4478)	0.17614987033920534
  (0, 4504)	0.08981790265631966
  (0, 31114)	0.09334755045058664
  :	:
  (9999, 15127)	0.11046059784194202
  (9999, 25630)	0.17004530601027332
  (9999, 13594)	0.13974147875726825
  (9999, 21023)	0.14569321239328797
  (9999, 19330)	0.15927705954339139
  (

Cosine Similarity

In [15]:
# Getting similarity Scores
similar=cosine_similarity(feature_vectors)

In [16]:
print(similar)

[[1.         0.05885183 0.05992742 ... 0.06916759 0.07300175 0.06197185]
 [0.05885183 1.         0.03657728 ... 0.02836902 0.02829776 0.02673311]
 [0.05992742 0.03657728 1.         ... 0.03354269 0.04731594 0.03101344]
 ...
 [0.06916759 0.02836902 0.03354269 ... 1.         0.03069412 0.01611449]
 [0.07300175 0.02829776 0.04731594 ... 0.03069412 1.         0.03603181]
 [0.06197185 0.02673311 0.03101344 ... 0.01611449 0.03603181 1.        ]]


In [17]:
print(similar.shape)

(10000, 10000)


In [18]:
# Getting movie name from user
user_movie=input("Enter movie name: ")

Enter movie name: Avatar


In [19]:
#List of movies
list_movies=movies_data['Name'].tolist()
print(list_movies)

['The Shawshank Redemption', 'Dilwale Dulhania Le Jayenge', 'The Godfather', "Schindler's List", 'The Godfather: Part II', 'Impossible Things', 'Spirited Away', 'Your Eyes Tell', 'Dou kyu sei – Classmates', 'Your Name.', '12 Angry Men', "Gabriel's Inferno", 'Parasite', 'The Green Mile', "Gabriel's Inferno: Part II", 'The Dark Knight', 'The Good, the Bad and the Ugly', 'Pulp Fiction', 'The Lord of the Rings: The Return of the King', "Gabriel's Inferno: Part III", 'Forrest Gump', 'Cinema Paradiso', 'Seven Samurai', 'GoodFellas', 'Violet Evergarden: The Movie', 'Life Is Beautiful', 'Once Upon a Time in America', 'Harakiri', 'Psycho', 'Josee, the Tiger and the Fish', "A Dog's Will", 'Grave of the Fireflies', "One Flew Over the Cuckoo's Nest", 'Fight Club', 'Evangelion: 3.0+1.0 Thrice Upon a Time', 'Spider-Man: Into the Spider-Verse', 'City of God', 'Hope', 'A Silent Voice: The Movie', 'Hotarubi no Mori e', "Howl's Moving Castle", 'Neon Genesis Evangelion: The End of Evangelion', 'The Empir

In [20]:
#finding closest matches of movie
close_movie_match=difflib.get_close_matches(user_movie, list_movies)
print(close_movie_match)

['Avatar', 'Ava', 'A Private War']


In [21]:
close_match=close_movie_match[0]
print(close_match)

Avatar


In [22]:
index_movie = movies_data[movies_data.Name == close_match]['index'].values[0]
print(index_movie)

1289


In [23]:
index_sort=sorted(list(enumerate(similar[index_movie])), reverse=True, key= lambda x:x[1])
print(index_sort)


[(1289, 0.9999999999999994), (9631, 0.16694526800575954), (2032, 0.14017521201060085), (142, 0.13966432533044087), (4158, 0.13734073447662692), (1912, 0.13308224471681127), (5040, 0.13291049446505684), (7217, 0.1321678364002816), (9609, 0.13086989977012875), (8232, 0.13025135912654207), (8086, 0.1268319958048173), (6727, 0.12358028543056541), (1533, 0.12067281980359755), (1230, 0.11938509978232123), (8956, 0.11700650581052997), (1312, 0.11642122346932413), (4639, 0.11555823849687993), (9741, 0.11531732411414539), (3013, 0.11429560999941837), (9850, 0.11408099372361119), (1019, 0.11326042888963374), (9145, 0.1121675665390081), (3976, 0.11059712126646792), (5891, 0.11006217546205425), (2407, 0.10996189922934548), (9713, 0.10892792429940099), (3696, 0.10807424162191022), (2968, 0.10641585584283392), (2056, 0.10421919405055774), (3085, 0.10291180116748842), (6825, 0.10246640079468525), (5779, 0.10204931282993937), (7658, 0.10203611170758792), (9029, 0.10101906656537289), (5553, 0.098457811

In [26]:
for i in index_sort[1:30]:
  print(movies_data.iloc[i[0]].Name)

West Side Story
Torque
The Night Before the Exams
C.R.A.Z.Y.
Shot Caller
50 First Dates
Splash
Homefront
The Legend of Hercules
The Tiger and the Snow
I Could Never Be Your Woman
All Dogs Go to Heaven
Venice Calling
Crouching Tiger, Hidden Dragon: Sword of Destiny
The Frighteners
Ex 2: Still Friends
Hercules
Love, Simon
I Want You
Vamps
Prizzi's Honor
Men, Women & Children
The 10 Year Plan
Jin-Roh: The Wolf Brigade
The Sisterhood of the Traveling Pants 2
The Crew
Amar
Madly in Love
The Last Kiss


In [27]:
user_movie=input("Enter movie name: ")

list_movies=movies_data['Name'].tolist()

close_movie_match=difflib.get_close_matches(user_movie, list_movies)

close_match=close_movie_match[0]

index_movie = movies_data[movies_data.Name == close_match]['index'].values[0]

index_sort=sorted(list(enumerate(similar[index_movie])), reverse=True, key= lambda x:x[1])

print("Movies recommended: \n")

for i in index_sort[0:30]:
  print(movies_data.iloc[i[0]].Name)

Enter movie name: Avengers
Movies recommended: 

The Avengers
Avengers: Age of Ultron
Enemy Mine
Kingsman: The Secret Service
Crime Busters
Justice Society: World War II
Echelon Conspiracy
Marvel One-Shot: The Consultant
Kingsman: The Golden Circle
The Matrix Resurrections
The Rookie
Eternals
Tom Clancy's Without Remorse
Allegiant
Push
The Fountain
Thor: Ragnarok
Spider-Man: Far From Home
Independence Day: Resurgence
F/X
Captain America: The Winter Soldier
The Losers
The One I Love
Kung Fury
2010
The Night House
Timecop
Wall Street: Money Never Sleeps
The Butterfly Effect 2
Are We There Yet?
